"""Crea un repo GitHub (si no existe) y publica multiples archivos en un commit.

Usa la API GitHub: /user/repos para crear, /repos/.../contents/{path} para cada
archivo. Si se proveen muchos archivos (>50), seria mejor usar el API low-level
de git data (blobs+tree+commit) pero para nuestro uso (~20 archivos por build)
es suficiente con contents.
"""
from __future__ import annotations

import base64
from typing import Any

import httpx

from shared.config.settings import settings


def _headers() -> dict[str, str]:
    return {
        "Authorization": f"Bearer {settings.scrumdev_git_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _configured() -> bool:
    return bool(settings.scrumdev_git_token and settings.scrumdev_git_owner)


async def ensure_repo(name: str, description: str = "", private: bool = True) -> dict[str, Any]:
    """Devuelve el repo. Si no existe e intenta crear, puede fallar por permisos."""
    if not _configured():
        return {"error": "GitHub no configurado. Setea SCRUMDEV_GIT_TOKEN y SCRUMDEV_GIT_OWNER."}
    owner = settings.scrumdev_git_owner
    repo_name = name.lower().replace("_", "-")[:100]

    async with httpx.AsyncClient(timeout=30.0) as client:
        existing = await client.get(
            f"https://api.github.com/repos/{owner}/{repo_name}", headers=_headers()
        )
        if existing.status_code == 200:
            return existing.json()

        create = await client.post(
            "https://api.github.com/user/repos",
            json={
                "name": repo_name,
                "description": description or f"Generated by ScrumDev AI for {name}",
                "private": private,
                "auto_init": True,
            },
            headers=_headers(),
        )
        if create.status_code == 403:
            return {
                "error": "github_token_insufficient_permissions",
                "message": (
                    "Tu PAT de GitHub no tiene permiso para crear repos. "
                    "Crea el repo manualmente en GitHub y vuelve a desplegar, "
                    "o actualiza el PAT con 'Administration: Read and Write'."
                ),
                "manual_create_url": f"https://github.com/new?name={repo_name}",
                "expected_repo": f"{owner}/{repo_name}",
            }
        if create.status_code >= 400:
            org_create = await client.post(
                f"https://api.github.com/orgs/{owner}/repos",
                json={"name": repo_name, "private": private, "auto_init": True},
                headers=_headers(),
            )
            if org_create.status_code >= 400:
                return {
                    "error": "create_failed",
                    "details": create.text[:300],
                    "manual_create_url": f"https://github.com/new?name={repo_name}",
                    "expected_repo": f"{owner}/{repo_name}",
                }
            return org_create.json()
        return create.json()


async def push_files(
    repo_name: str, files: list[dict], branch: str = "main", commit_message: str = "feat: ScrumDev AI generated"
) -> dict[str, Any]:
    """Hace upsert de cada archivo en main. Para cada file: {path, content}."""
    if not _configured():
        return {"error": "GitHub no configurado."}
    owner = settings.scrumdev_git_owner
    repo = repo_name.lower().replace("_", "-")[:100]
    pushed: list[dict] = []
    failed: list[dict] = []

    async with httpx.AsyncClient(timeout=60.0) as client:
        for f in files:
            path = f.get("path") or f.get("file_path")
            content = f.get("content", "")
            if not path:
                continue
            # Check if file exists para obtener SHA
            existing = await client.get(
                f"https://api.github.com/repos/{owner}/{repo}/contents/{path}",
                params={"ref": branch},
                headers=_headers(),
            )
            sha = existing.json().get("sha") if existing.status_code == 200 else None

            payload: dict[str, Any] = {
                "message": f"{commit_message} :: {path}",
                "content": base64.b64encode(content.encode()).decode(),
                "branch": branch,
            }
            if sha:
                payload["sha"] = sha

            r = await client.put(
                f"https://api.github.com/repos/{owner}/{repo}/contents/{path}",
                json=payload,
                headers=_headers(),
            )
            if r.status_code in (200, 201):
                data = r.json()
                pushed.append({"path": path, "sha": data.get("commit", {}).get("sha")})
            else:
                failed.append({"path": path, "error": r.text[:200]})

    return {
        "repo": f"{owner}/{repo}",
        "branch": branch,
        "pushed_count": len(pushed),
        "failed_count": len(failed),
        "pushed": pushed,
        "failed": failed,
        "url": f"https://github.com/{owner}/{repo}",
    }
