"""State machine del ciclo de vida de una historia.

Estados (segun documento maestro Parte C.7):

  BACKLOG -> REFINEMENT -> NFR_CAPTURE -> ARCHITECTURE_INCEPTION
    -> ARCHITECTURE_APPROVAL_PENDING -> READY_FOR_DEVELOPMENT
    -> DEVELOPMENT -> CODE_REVIEW -> QA -> PO_REVIEW
    -> RELEASE_APPROVAL_PENDING -> STAGING_DEPLOYMENT
    -> PRODUCTION_DEPLOYMENT -> RELEASED

Cualquier estado puede transicionar a FAILED.

`TRANSITIONS` define las transiciones permitidas. `next_state()` devuelve el
siguiente estado natural; `can_transition()` valida un cambio arbitrario.
"""
from __future__ import annotations

from shared.events.event_types import (
    WORKFLOW_STATE_ARCHITECTURE_APPROVAL,
    WORKFLOW_STATE_ARCHITECTURE_INCEPTION,
    WORKFLOW_STATE_BACKLOG,
    WORKFLOW_STATE_CODE_REVIEW,
    WORKFLOW_STATE_DEVELOPMENT,
    WORKFLOW_STATE_FAILED,
    WORKFLOW_STATE_NFR_CAPTURE,
    WORKFLOW_STATE_PO_REVIEW,
    WORKFLOW_STATE_PRODUCTION_DEPLOY,
    WORKFLOW_STATE_QA,
    WORKFLOW_STATE_READY_FOR_DEV,
    WORKFLOW_STATE_REFINEMENT,
    WORKFLOW_STATE_RELEASE_APPROVAL,
    WORKFLOW_STATE_RELEASED,
    WORKFLOW_STATE_STAGING_DEPLOY,
)

NEXT_STATE: dict[str, str] = {
    WORKFLOW_STATE_BACKLOG: WORKFLOW_STATE_REFINEMENT,
    WORKFLOW_STATE_REFINEMENT: WORKFLOW_STATE_NFR_CAPTURE,
    WORKFLOW_STATE_NFR_CAPTURE: WORKFLOW_STATE_ARCHITECTURE_INCEPTION,
    WORKFLOW_STATE_ARCHITECTURE_INCEPTION: WORKFLOW_STATE_ARCHITECTURE_APPROVAL,
    WORKFLOW_STATE_ARCHITECTURE_APPROVAL: WORKFLOW_STATE_READY_FOR_DEV,
    WORKFLOW_STATE_READY_FOR_DEV: WORKFLOW_STATE_DEVELOPMENT,
    WORKFLOW_STATE_DEVELOPMENT: WORKFLOW_STATE_CODE_REVIEW,
    WORKFLOW_STATE_CODE_REVIEW: WORKFLOW_STATE_QA,
    WORKFLOW_STATE_QA: WORKFLOW_STATE_PO_REVIEW,
    WORKFLOW_STATE_PO_REVIEW: WORKFLOW_STATE_RELEASE_APPROVAL,
    WORKFLOW_STATE_RELEASE_APPROVAL: WORKFLOW_STATE_STAGING_DEPLOY,
    WORKFLOW_STATE_STAGING_DEPLOY: WORKFLOW_STATE_PRODUCTION_DEPLOY,
    WORKFLOW_STATE_PRODUCTION_DEPLOY: WORKFLOW_STATE_RELEASED,
    WORKFLOW_STATE_RELEASED: WORKFLOW_STATE_RELEASED,
}

PENDING_HUMAN_APPROVAL = {
    WORKFLOW_STATE_ARCHITECTURE_APPROVAL,
    WORKFLOW_STATE_RELEASE_APPROVAL,
}

CREW_BY_STATE: dict[str, str] = {
    WORKFLOW_STATE_REFINEMENT: "refinement",
    WORKFLOW_STATE_ARCHITECTURE_INCEPTION: "architecture",
    WORKFLOW_STATE_DEVELOPMENT: "delivery",
    WORKFLOW_STATE_CODE_REVIEW: "delivery",
    WORKFLOW_STATE_QA: "delivery",
}


def next_state(current: str) -> str:
    return NEXT_STATE.get(current, WORKFLOW_STATE_FAILED)


def can_transition(current: str, target: str) -> bool:
    if target == WORKFLOW_STATE_FAILED:
        return True
    return NEXT_STATE.get(current) == target


def requires_human_approval(state: str) -> bool:
    return state in PENDING_HUMAN_APPROVAL


def crew_for_state(state: str) -> str | None:
    return CREW_BY_STATE.get(state)
