HUMAN_MESSAGE_RECEIVED = "HUMAN_MESSAGE_RECEIVED"
WORKFLOW_STARTED = "WORKFLOW_STARTED"
WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
ISSUE_REFINEMENT_REQUESTED = "ISSUE_REFINEMENT_REQUESTED"
ARCHITECTURE_REQUESTED = "ARCHITECTURE_REQUESTED"
AGENT_EXECUTION_REQUESTED = "AGENT_EXECUTION_REQUESTED"
AGENT_EXECUTION_STARTED = "AGENT_EXECUTION_STARTED"
AGENT_EXECUTION_COMPLETED = "AGENT_EXECUTION_COMPLETED"
AGENT_EXECUTION_FAILED = "AGENT_EXECUTION_FAILED"
HUMAN_APPROVAL_REQUIRED = "HUMAN_APPROVAL_REQUIRED"
HUMAN_APPROVAL_GRANTED = "HUMAN_APPROVAL_GRANTED"
HUMAN_APPROVAL_REJECTED = "HUMAN_APPROVAL_REJECTED"

NFR_CAPTURED = "NFR_CAPTURED"
ARCHITECTURE_PROPOSED = "ARCHITECTURE_PROPOSED"
ARCHITECTURE_APPROVED = "ARCHITECTURE_APPROVED"
ADR_GENERATED = "ADR_GENERATED"
POLICY_VIOLATION_DETECTED = "POLICY_VIOLATION_DETECTED"
RELEASE_APPROVED = "RELEASE_APPROVED"
STAGING_DEPLOYED = "STAGING_DEPLOYED"
PRODUCTION_DEPLOYED = "PRODUCTION_DEPLOYED"
RELEASED = "RELEASED"

# Eventos canonicos de la guia Delfin (§4.2) — hitos del ciclo Scrum
ISSUE_CREATED = "ISSUE_CREATED"
ISSUE_REFINED = "ISSUE_REFINED"
DEVELOPMENT_STARTED = "DEVELOPMENT_STARTED"
PULL_REQUEST_CREATED = "PULL_REQUEST_CREATED"
CODE_REVIEW_COMPLETED = "CODE_REVIEW_COMPLETED"
QA_COMPLETED = "QA_COMPLETED"

# Lista canonica completa de eventos de dominio (para validacion/cobertura)
GUIDE_DOMAIN_EVENTS = [
    ISSUE_CREATED, ISSUE_REFINED, ARCHITECTURE_APPROVED, DEVELOPMENT_STARTED,
    PULL_REQUEST_CREATED, CODE_REVIEW_COMPLETED, QA_COMPLETED,
    HUMAN_APPROVAL_REQUIRED, RELEASE_APPROVED, STAGING_DEPLOYED,
    PRODUCTION_DEPLOYED, WORKFLOW_COMPLETED,
]

WORKFLOW_STATE_BACKLOG = "BACKLOG"
WORKFLOW_STATE_REFINEMENT = "REFINEMENT"
WORKFLOW_STATE_NFR_CAPTURE = "NFR_CAPTURE"
WORKFLOW_STATE_ARCHITECTURE_INCEPTION = "ARCHITECTURE_INCEPTION"
WORKFLOW_STATE_ARCHITECTURE_APPROVAL = "ARCHITECTURE_APPROVAL_PENDING"
WORKFLOW_STATE_READY_FOR_DEV = "READY_FOR_DEVELOPMENT"
WORKFLOW_STATE_DEVELOPMENT = "DEVELOPMENT"
WORKFLOW_STATE_CODE_REVIEW = "CODE_REVIEW"
WORKFLOW_STATE_QA = "QA"
WORKFLOW_STATE_PO_REVIEW = "PO_REVIEW"
WORKFLOW_STATE_RELEASE_APPROVAL = "RELEASE_APPROVAL_PENDING"
WORKFLOW_STATE_STAGING_DEPLOY = "STAGING_DEPLOYMENT"
WORKFLOW_STATE_PRODUCTION_DEPLOY = "PRODUCTION_DEPLOYMENT"
WORKFLOW_STATE_RELEASED = "RELEASED"
WORKFLOW_STATE_FAILED = "FAILED"

ALL_WORKFLOW_STATES = [
    WORKFLOW_STATE_BACKLOG,
    WORKFLOW_STATE_REFINEMENT,
    WORKFLOW_STATE_NFR_CAPTURE,
    WORKFLOW_STATE_ARCHITECTURE_INCEPTION,
    WORKFLOW_STATE_ARCHITECTURE_APPROVAL,
    WORKFLOW_STATE_READY_FOR_DEV,
    WORKFLOW_STATE_DEVELOPMENT,
    WORKFLOW_STATE_CODE_REVIEW,
    WORKFLOW_STATE_QA,
    WORKFLOW_STATE_PO_REVIEW,
    WORKFLOW_STATE_RELEASE_APPROVAL,
    WORKFLOW_STATE_STAGING_DEPLOY,
    WORKFLOW_STATE_PRODUCTION_DEPLOY,
    WORKFLOW_STATE_RELEASED,
    WORKFLOW_STATE_FAILED,
]
